TagesschauBlocker added
dieparteidiepartei/afd-blocker-plugin pull request #17
Opened 2019-05-13 17:37 UTC by lennart-k

Auch auf tagesschau.de freue ich mich über eine aufgeräumte News-Liste

2019-05-13 21:23 UTC, dieparteidiepartei requested changes
Thanks for the work! Please add more selectors for different teaser types and articles.

2019-05-13 21:23 UTC, dieparteidiepartei commented on app/scripts/blocker_tagesschau.js
> +]);
I can find some elements that are not blocked by this:
* Article Pages
* TOP 5 lists next to an article

2019-05-13 21:23 UTC, dieparteidiepartei commented on app/scripts/blocker_faz.js
> +]);
This only matches one teaser type. There are many more on faz.net

2019-05-28 21:22 UTC, lennart-k commented
Dachte, das könnte man ja immernoch im Nachhinein machen.
Aktuell ist da nur eben überhaupt nichts als Maßnahme bei tagesschau.de

2021-09-21 16:37 UTC, closed without merging